### ISSUE TITLE
iOS and iCloud

### ISSUE THREAD

**Issue by rafaellop** [object-layer/cordova-sqlite-plugin#4]
Hi,

Is your plugin compatible with the iOS guidelines regarding iCloud backup which prohibits database backups to iCloud?

https://developer.apple.com/library/mac/documentation/General/Conceptual/iCloudDesignGuide/Chapters/iCloudFundametals.html

I'm about to choose a storage plugin for my app and I'd like to know.

Cheers,
Rafal

**Comment by mvila** [comment]
Hi @rafaellop! This plugin is based on [cordova-sqlite-storage](https://github.com/litehelpers/Cordova-sqlite-storage) and since I use `'nosync'` as `dblocation` the database should not be backed up by iCloud.
