### ISSUE TITLE
How to safely delete the database file

### ISSUE THREAD

**Issue by yyfearth** [object-layer/cordova-sqlite-plugin#5]
As compare to the original cordova sqlite storage plugin, is there a way to delete the database file for this plugin?

**Comment by mvila** [comment]
No, sorry, this is not possible to delete the database file. Maybe you could just delete all tables?

**Comment by yyfearth** [comment]
Thanks for reply, could you tell me where is the db file located on iOS/Android with given name for the SQLite constructor? So I can located it from the FS and delete it via cordova file plugin.

**Comment by mvila** [comment]
It should be at the same location as [cordova-sqlite-storage](https://github.com/litehelpers/Cordova-sqlite-storage). Sorry, I don't now the internal details.
